[target.x86_64-unknown-linux-musl]
pre-build = ["DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake perl pkg-config libclang-dev"]
env.passthrough = [
    "CC_x86_64_unknown_linux_musl",
    "CXX_x86_64_unknown_linux_musl",
    "CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER"
]

[target.aarch64-unknown-linux-musl]
pre-build = ["DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake perl pkg-config libclang-dev"]

[target.armv7-unknown-linux-musleabihf]
pre-build = ["DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake perl pkg-config libclang-dev"]
